name: pos_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

# All the package should place here for production
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.1.2
  google_fonts: ^5.1.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  intl: ^0.18.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  http: ^1.1.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  flutter_svg: ^2.0.7
  flare_flutter: ^3.0.2
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  pedantic: ^1.11.1

# Dev package for debugging
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  test: ^1.24.1
  bloc_test: ^9.1.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  # To add assets to your application,
  assets:
    - assets/
    - assets/icon/
    - assets/dash_icon/
    - assets/languages/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
